//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Categories = new HashSet<Category>();
            this.Images = new HashSet<Image>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Description { get; set; }
        public string EventUrl { get; set; }
        public byte State { get; set; }
        public Nullable<int> AttendingCount { get; set; }
        public Nullable<int> VenueId { get; set; }
        public Nullable<int> VenueId1 { get; set; }
        public byte Version { get; set; }
    
        public virtual Venue Venue { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
