//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventz.Data
{
    using System;
    
    public enum StorageType : byte
    {
        Facebook = 0,
        Meetup = 1,
        ClubZone = 2
    }
}
